image: openjdk:22-ea-6-jdk-oraclelinux8
# https://hub.docker.com/_/openjdk
stages: 
  - build
  - test
  - deploy

launch-script:
  stage: test
  script:
    - echo "Logued in as $GITLAB_USER_LOGIN!"
    - cd /path
    - ./script.sh
    # sleep? 

script-2:
  stage: build
  script:
    - cd ../path/
    - CARTRIDGE_NAME=$(ls -t | awk '{print $3 }') 
    - echo 'Deploying ... $CARTRIDGE_NAME' 
    - deploy_script.sh

test-cartridge:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - sleep 20

deploy-prod:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@ip.99 " #user/ip can be stored as variables


