name: executing remote ssh commands using password
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Connect
      uses: actions/checkout@v3
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: docker stop c196fa48cb19
